baseURL = "https://meetyavie.netlify.app/"
languageCode = "de-de"
title = "Yavie"
theme = "ananke"

paginate = 10

[params]
  description = "Hi, ich bin Yavie."
  featured_image = "/images/yavie-hero.jpg"
  show_reading_time = true
