baseURL = "https://iridescent-brioche-e52c28.netlify.app/"
languageCode = "de-de"
title = "Yavie"

paginate = 10

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[ananke.social]
icon_path = "ananke/socials/%s.svg"

[ananke.social.networks.instagram]
slug = "instagram"
label = "Instagram"
color = "#e1306c"
profile = "https://www.instagram.com/%s/"
icon = "instagram" # font awesome brand icon name



[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
