baseURL = "https://iridescent-brioche-e52c28.netlify.app/"
languageCode = "de-de"
title = "Yavie"

paginate = 10

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
