baseURL = "https://iridescent-brioche-e52c28.netlify.app/"
languageCode = "de-DE"
title = "Yavie Hoffmann"

paginate = 10

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[ananke.social.follow]
networks = ["instagram"]

[params]
description = "Gedanken, Geschichten und Perspektiven aus einer nahen Zukunft."
featured_image = "/images/yavie-hero.jpg"
background_color_class = "bg-black"
text_color_class = "text-white"
show_reading_time = true
mainSections = ["posts"]

# Share Icons (ARTIKEL TEILEN)
showShareIcons = true
shareIcons = ["email", "linkedin", "facebook", "twitter"]

instagram = "meetyavie"


[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
