baseURL = "https://iridescent-brioche-e52c28.netlify.app/"
languageCode = "de-de"
title = "Yavie"

paginate = 10

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[params]
  description = "Hi, I'm Yavie."
  featured_image = "/images/yavie-hero.jpg"
  background_color_class = "bg-black"
  text_color_class = "text-white"
  show_reading_time = true
